name: Create Release

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Tag name'
        required: true  
  push:
    tags:
      - 'v*'

jobs:
  create_release:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Get previous tag
      id: prev-tag
      run: |
        echo ::set-output name=prev_tag::$(git describe --tags --abbrev=0 $(git rev-list --tags --skip=1 --max-count=1))

    - name: Generate release notes
      id: release-notes
      run: |
        prev_tag=${{ steps.prev-tag.outputs.prev_tag }}
        current_tag=${{ github.event.inputs.tag_name || github.ref_name }}
        release_notes=$(git log $prev_tag..$current_tag --oneline)
        echo "::set-output name=release_notes::$release_notes"

    - name: Create GitHub Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.event.inputs.tag_name || github.ref_name }}
        release_name: ${{ github.event.inputs.tag_name || github.ref_name }}
        body: ${{ steps.release-notes.outputs.release_notes }}