name: SonarCloud Analysis

on:
  push:
    branches:
      - main
      - 12-fix-sonarcloud-scan
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  sonarcloud:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          sonar.host.url: https://sonarcloud.io 
          sonar.organization: brainupgrade-in
          sonar.projectKey: brainupgrade-in_copilot_weather
        with:
          args: >
            -Dsonar.branch.name=${{ github.ref_name }}
            -X      